UrunSatisOtomasyon/Models/Kullanici.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UrunSatisOtomasyon.Models
{
    public class Kullanici
    {
        public int id { get; set; }
        [Display(Name = "Kullanıcı Adı")]
        [Required]
        public string Ad { get; set; }
        [Display(Name = "Sifre")]
        [Required]
        public string Sifre { get; set; }
    }
}

UrunSatisOtomasyon/Areas/Admin/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UrunSatisOtomasyon.DAL;
using UrunSatisOtomasyon.Models;

namespace UrunSatisOtomasyon.Areas.Admin.Controllers
{
    public class KullaniciController:Controller
    {
        PersonelContext ctx = new PersonelContext();
        public ActionResult Kayit()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Kayit(Kullanici klc)
        {
            if (ModelState.IsValid)
            {
                ctx.Kullanicilar.Add(klc);
                int sonuc = ctx.SaveChanges();
                if (sonuc > 0)
                {
                    return RedirectToAction("Login", "Giris");
                }
            }
            return View();
        }
    }
}

UrunSatisOtomasyon/Areas/Admin/Views/Kullanici/Kayit.cshtml
@model UrunSatisOtomasyon.Models.Kullanici

@{
    ViewBag.Title = "Kayıt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Kayıt</h2>

@using (Html.BeginForm("Kayit", "Kullanici", FormMethod.Post))
{

    <div class="form-group">
        @Html.LabelFor(o => o.Ad);
        @Html.TextBoxFor(o => o.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Ad)
        <label id="lblAdHata" style="display:none;color:red">Ad alanı boş olamaz</label>

    </div>
    <div class="form-group">
        @Html.LabelFor(o => o.Sifre);
        @Html.TextBoxFor(o => o.Sifre, new { @type = "password", @class = "form-control" })
        @Html.ValidationMessageFor(o => o.Sifre)
        <label id="lblHata" style="display:none;color:red">Şifre alanı boş olamaz</label>

    </div>
    <input type="submit" name="btnKaydet" value="Kaydol" class="btn btn-danger" onclick="return BoslukKontrol()" />

}

@section scripts{
    <script>
       function BoslukKontrol() {
           var hatayok = true;
           if ($("#Ad").val() == ""||$("#Sifre").val() == "") {
               $("#lblAdHata").show();
               $("#lblHata").show();
               hatayok = false;
           }

           return hatayok;
       }

    </script>

}